/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Molecules/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardProduct: typeof import('./components/Atoms/CardProduct.vue')['default']
    CardStep: typeof import('./components/Atoms/CardStep.vue')['default']
    CategoryProduct: typeof import('./components/Projects/CreateStep/CategoryProduct.vue')['default']
    Create: typeof import('./components/Projects/Create.vue')['default']
    Customer: typeof import('./components/Projects/CreateStep/Customer.vue')['default']
    DialogAddMaterial: typeof import('./components/Atoms/DialogAddMaterial.vue')['default']
    DialogAddStep: typeof import('./components/Atoms/DialogAddStep.vue')['default']
    Drawer: typeof import('./components/Molecules/Drawer.vue')['default']
    EditProjectDetail: typeof import('./components/Projects/EditProjectDetail.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Material: typeof import('./components/Projects/CreateStep/Material.vue')['default']
    Negosiasi: typeof import('./components/Projects/Negosiasi.vue')['default']
    Ongoing: typeof import('./components/Projects/Ongoing.vue')['default']
    Product: typeof import('./components/Projects/CreateStep/Product.vue')['default']
    ProjectCard: typeof import('./components/Projects/ProjectCard.vue')['default']
    ProjectDetail: typeof import('./components/Projects/ProjectDetail.vue')['default']
    ProjectTabs: typeof import('./components/Molecules/ProjectTabs.vue')['default']
    Result: typeof import('./components/Projects/CreateStep/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./components/Projects/CreateStep/Step.vue')['default']
    SummaryCard: typeof import('./components/Atoms/SummaryCard.vue')['default']
    TextWithIcon: typeof import('./components/Atoms/TextWithIcon.vue')['default']
    Toolbar: typeof import('./components/Molecules/Toolbar.vue')['default']
    Tools: typeof import('./components/Projects/CreateStep/Tools.vue')['default']
    UnduhPdf: typeof import('./components/Projects/UnduhPdf.vue')['default']
    WaitingSuevey: typeof import('./components/Projects/WaitingSuevey.vue')['default']
    WaitingSurvey: typeof import('./components/Projects/WaitingSurvey.vue')['default']
    Worker: typeof import('./components/Projects/CreateStep/Worker.vue')['default']
  }
}
