/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Molecules/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardEstimasi: typeof import('./components/Projects/CardEstimasi.vue')['default']
    CardProduct: typeof import('./components/Atoms/CardProduct.vue')['default']
    CardStep: typeof import('./components/Atoms/CardStep.vue')['default']
    CategoryProduct: typeof import('./components/Projects/CreateEstimasi/CategoryProduct.vue')['default']
    copy: typeof import('./components/Projects/WaitingSurvey copy.vue')['default']
    Create: typeof import('./components/Projects/Create.vue')['default']
    CreateEstimasi: typeof import('./components/Projects/createEstimasi.vue')['default']
    Customer: typeof import('./components/Projects/CreateEstimasi/Customer.vue')['default']
    DataCostumer: typeof import('./components/Projects/CreateEstimasi/DataCostumer.vue')['default']
    DialogAddMaterial: typeof import('./components/Atoms/DialogAddMaterial.vue')['default']
    DialogAddStep: typeof import('./components/Atoms/DialogAddStep.vue')['default']
    Done: typeof import('./components/Projects/done.vue')['default']
    Drawer: typeof import('./components/Molecules/Drawer.vue')['default']
    EditProjectDetail: typeof import('./components/Projects/EditProjectDetail.vue')['default']
    Estimasi: typeof import('./components/Projects/Estimasi.vue')['default']
    EstimasiDetail: typeof import('./components/Projects/EstimasiDetail.vue')['default']
    HasilJadwal: typeof import('./components/Projects/HasilJadwal.vue')['default']
    HasilSurvey: typeof import('./components/Projects/HasilSurvey.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Jadwal: typeof import('./components/Projects/Jadwal.vue')['default']
    Material: typeof import('./components/Projects/CreateEstimasi/Material.vue')['default']
    Negosiasi: typeof import('./components/Projects/Negosiasi.vue')['default']
    Ongoing: typeof import('./components/Projects/Ongoing.vue')['default']
    Product: typeof import('./components/Projects/CreateEstimasi/Product.vue')['default']
    ProjectCard: typeof import('./components/Projects/ProjectCard.vue')['default']
    ProjectCardDone: typeof import('./components/Projects/ProjectCardDone.vue')['default']
    ProjectCardEstimasi: typeof import('./components/Projects/ProjectCardEstimasi.vue')['default']
    ProjectCardWaiting: typeof import('./components/Projects/ProjectCardWaiting.vue')['default']
    ProjectDetail: typeof import('./components/Projects/ProjectDetail.vue')['default']
    ProjectTabs: typeof import('./components/Molecules/ProjectTabs.vue')['default']
    Result: typeof import('./components/Projects/CreateEstimasi/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./components/Projects/CreateEstimasi/Step.vue')['default']
    SummaryCard: typeof import('./components/Atoms/SummaryCard.vue')['default']
    TabsPage: typeof import('./components/Projects/tabsPage.vue')['default']
    TextWithIcon: typeof import('./components/Atoms/TextWithIcon.vue')['default']
    Toolbar: typeof import('./components/Molecules/Toolbar.vue')['default']
    Tools: typeof import('./components/Projects/CreateEstimasi/Tools.vue')['default']
    Ukuran: typeof import('./components/Projects/CreateEstimasi/Ukuran.vue')['default']
    UnduhPdf: typeof import('./components/Projects/UnduhPdf.vue')['default']
    Waiting: typeof import('./components/Projects/waiting.vue')['default']
    WaitingSurvey: typeof import('./components/Projects/WaitingSurvey.vue')['default']
    'WaitingSurvey copy': typeof import('./components/Projects/WaitingSurvey copy.vue')['default']
    Worker: typeof import('./components/Projects/CreateEstimasi/Worker.vue')['default']
  }
}
